version: "3.2"

networks: 
  frontend:
  backend:

services:
  catalog:
    build:
      context: .\src\Services\ProductCatalogApi
      dockerfile: Dockerfile
    image: shoes/catalog
    environment:
      - DatabaseServer=mssqlserver
      - DatabaseName=CatalogDb
      - DatabaseUser=sa
      - DatabaseUserPassword=ProductApi(!)
    container_name: catalogapi
    ports:
      - "5000:80"
    networks: 
      - backend
      - frontend
    depends_on:
      - mssqlserver
      
  mssqlserver:
    build:
      context: .\src\Db
      dockerfile: Dockerfile
    ports: 
      - "1435:1433"
    container_name: mssqlcontainer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ProductApi(!)
    healthcheck:
      test: sqlcmd -S db1.internal.prod.example.com -U SA -P 'Alaska2017' -Q 'select 1'
    networks:
      - backend